name: build_recastdll

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  osx_navmesh:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Download & install SDL
        run: |
          curl -L -o SDL2.dmg https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-2.24.2.dmg
          hdiutil attach SDL2.dmg
          cp -r /Volumes/SDL2/SDL2.framework ${{github.workspace}}/RecastDemo/Bin/
          hdiutil detach /Volumes/SDL2
          rm SDL2.dmg
      - name: Build
        working-directory: RecastCustom/NavMeshExport
        run: ./make_osx.sh 
      - name: UploadNavMeshExport
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/NavMeshExport/Plugins/**/*
          name: plugin_NavMeshExport
  linux_navmesh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install lib
        run: sudo apt-get update && sudo apt-get install -y libgl1-mesa-dev libsdl2-dev
      - name: Build
        working-directory: RecastCustom/NavMeshExport
        run: ./make_linux64.sh
      - name: UploadNavMeshExport
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/NavMeshExport/Plugins/**/*
          name: plugin_NavMeshExport
  linux_navmesh32:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install 32-bit support and other lib
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib libgl1-mesa-dev:i386 libsdl2-dev:i386
      - name: Build
        working-directory: RecastCustom/NavMeshExport
        run: ./make_linux32.sh
      - name: UploadNavMeshExport
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/NavMeshExport/Plugins/**/*
          name: plugin_NavMeshExport
  windows_navmesh:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1

      - name: Download and Install SDL
        working-directory: RecastDemo/Contrib
        shell: pwsh
        run: |
          (new-object System.Net.WebClient).DownloadFile("https://github.com/libsdl-org/SDL/releases/download/release-2.24.2/SDL2-devel-2.24.2-VC.zip","${{github.workspace}}/RecastDemo/Contrib/SDL.zip")
          tar -xf SDL.zip
          ren SDL2-2.24.2 SDL
          del SDL.zip
      
      - name: Build
        run: |
          cd RecastCustom/NavMeshExport
          .\make_win32.bat
          .\make_win64.bat
      - name: UploadNavMeshExport
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/NavMeshExport/Plugins/**/*
          name: plugin_NavMeshExport
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        working-directory: RecastCustom/RecastDll
        run: ./make_android.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/RecastDll/Plugins/**/*
          name: plugin_recastdll
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: RecastCustom/RecastDll
        run: ./make_ios.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/RecastDll/Plugins/**/*
          name: plugin_recastdll
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        working-directory: RecastCustom/RecastDll
        run: ./make_osx.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/RecastDll/Plugins/**/*
          name: plugin_recastdll
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install 32-bit support
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib
      - name: Build
        run: |
          cd RecastCustom/RecastDll
          ./make_linux32.sh
          ./make_linux64.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/RecastDll/Plugins/**/*
          name: plugin_recastdll   
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build
        run: |
          cd RecastCustom/RecastDll
          .\make_win32.bat
          .\make_win64.bat
          .\make_uwp.bat
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastCustom/RecastDll/Plugins/**/*
          name: plugin_recastdll   

  publish:
    runs-on: ubuntu-latest
    needs: [windows,osx,linux,ios,android,windows_navmesh,osx_navmesh,linux_navmesh]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: plugin_recastdll
          path: plugin_recastdll/
          
      - name: UploadRecastDll
        uses: actions/download-artifact@v3
        with:
          name: plugin_NavMeshExport
          path: plugin_NavMeshExport/
          
      - name: Create Release Asset
        run: |
          tar cvfz recastdll_${{ github.event.inputs.tag_name }}.tgz plugin_recastdll
          tar cvfz navmeshexport_${{ github.event.inputs.tag_name }}.tgz plugin_NavMeshExport

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          tag_name: ${{ github.event.inputs.tag_name }}
          files: |
            ./recastdll_${{ github.event.inputs.tag_name }}.tgz
            ./navmeshexport_${{ github.event.inputs.tag_name }}.tgz
            
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
