name: build_recastdll

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'tag name'     
        required: true

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install NDK
        run: |
          cd ~
          wget -O NDK -q https://dl.google.com/android/repository/android-ndk-r15c-linux-x86_64.zip
          sudo apt install unzip -y
          unzip -q NDK
          ANDROID_NDK_HOME=$(pwd)/android-ndk-r15c
      - name: Build
        run: |
          cd RecastDll
          ./make_android.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastDll/Plugins/**/*
          name: plugin_recastdll
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd RecastDll
          ./make_ios.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastDll/Plugins/**/*
          name: plugin_recastdll
  osx:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd RecastDll
          ./make_osx.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastDll/Plugins/**/*
          name: plugin_recastdll
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install 32-bit support
        run: sudo apt-get update && sudo apt-get install -y gcc-multilib g++-multilib
      - name: Build
        run: |
          cd RecastDll
          ./make_linux32.sh
          ./make_linux64.sh
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastDll/Plugins/**/*
          name: plugin_recastdll   
  windows:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3
      
      - name: Insatll MSVC
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Build
        run: |
          cd RecastDll
          .\make_win32.bat
          .\make_win64.bat
          .\make_uwp.bat
      - name: UploadRecastDll
        uses: actions/upload-artifact@v3
        with:
          path: ./RecastDll/Plugins/**/*
          name: plugin_recastdll   

  publish:
    runs-on: ubuntu-latest
    needs: [windows,osx,ios,android]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: plugin_recastdll
          path: plugin_recastdll/
          
      - name: Create Release Asset
        run: |
          tar cvfz recastdll_${{ github.event.inputs.tag_name }}.tgz plugin_recastdll

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # 将下述可执行文件 release 上去
          tag_name: ${{ github.event.inputs.tag_name }}
          files: ./recastdll_${{ github.event.inputs.tag_name }}.tgz
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
